name: 'Bark App'
description: 'An action for bark'
author: monlor <me@monlor.com>
branding:
  icon: 'message-circle'
  color: 'red'
inputs:
  host: 
    description: bark service host
    required: false
  key:
    description: Secret key
    required: true
  title:
    description: Message title
    required: false
  body:
    description: Message body
    required: false
  sound:
    description: Message sound
    required: false
  isArchive:
    description: Whether to archive this message
    required: false
  url:
    description: URL to redirect
    required: false
  automaticallyCopy:
    description: Whether to copy this message automatically
    required: false
  copy:
    description: Content copied to clipboard
    required: false
  icon:
    description: Message icon (ver >= ios15)
    required: false
  group:
    description: Message group
    required: false
runs:
  using: "composite"
  steps:
    - name: Run script
      shell: bash
      run: $GITHUB_ACTION_PATH/script.sh
      env: 
        INPUT_HOST: ${{ inputs.host }}
        INPUT_KEY: ${{ inputs.key }}
        INPUT_TITLE: ${{ inputs.title }}
        INPUT_BODY: ${{ inputs.body }}
        INPUT_SOUND: ${{ inputs.sound }}
        INPUT_ISARCHIVE: ${{ inputs.isArchive }}
        INPUT_URL: ${{ inputs.url }}
        INPUT_AUTOMATICALLYCOPY: ${{ inputs.automaticallyCopy }}
        INPUT_COPY: ${{ inputs.copy }}
        INPUT_ICON: ${{ inputs.icon }}
        INPUT_GROUP: ${{ inputs.group }}